import Head from "next/head";
import { makeStyles } from "@mui/styles";
import { Typography, Button } from "@mui/material";
import Link from "next/link";

const useStyles = makeStyles((theme) => ({
  red: {
    color: theme.palette.primary.main,
  },
  purple: {
    color: theme.palette.secondary.main,
  },
}));

export default function Home() {
  const classes = useStyles();
  return (
    <div className="pt-6 space-y-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1">h1 tag</Typography>
      <Typography variant="h2">h2 tag</Typography>
      <Typography variant="h3">h3 tag</Typography>
      <Typography variant="h4">h4 tag</Typography>
      <Typography variant="h5">h5 tag</Typography>
      <Typography variant="h6">h6 tag</Typography>
      <Typography variant="body1">body1 tag</Typography>
      <Typography variant="body2">body2 tag</Typography>
      <Typography variant="subtitle1">subtitle1 tag</Typography>
      <Typography variant="h1" className={classes.red}>
        Red
      </Typography>
      <Typography variant="h1" className={classes.purple}>
        Purple
      </Typography>
      <div className="text-3xl text-green-600 p-2">Hello Geeks!</div>{" "}
      <Link href="/about">
        <Button>About</Button>
      </Link>
    </div>
  );
}
